name: Publish Docker images to GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read package version
        id: pkg
        run: |
          echo "package_version=$(jq -r .version < src/package.json)" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push regular image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}/nodejs-docker-demo:latest
            ghcr.io/${{ github.repository }}/nodejs-docker-demo:${{ github.sha }}
            ghcr.io/${{ github.repository }}/nodejs-docker-demo:${{ steps.pkg.outputs.package_version }}

      - name: Build & push OTEL image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.otel
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}/nodejs-docker-demo-otel:latest
            ghcr.io/${{ github.repository }}/nodejs-docker-demo-otel:${{ github.sha }}
            ghcr.io/${{ github.repository }}/nodejs-docker-demo-otel:${{ steps.pkg.outputs.package_version }}

